spring:
  application:
    name: Prueba_Classora
server:
  port: 8082

r2dbc:
  url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password:

sql:
  init:
    mode: always

h2:
  console:
    enabled: true

codec:
  default-json-in-memory-size: 5MB

resilience4j:
  circuitbreaker:
    instances:
      priceService:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10

app:
  security:
    user: classoraUser
    pass: classoraPass
